<a href="https://colab.research.google.com/github/ash7-g/AI-1BM23CS400/blob/main/misplaced1BM23CS400.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import heapq
import numpy as np

class PuzzleState:
    def __init__(self, board, parent=None, move=0, cost=0):
        self.board = board
        self.parent = parent
        self.move = move
        self.cost = cost
        self.emptyTile = self.findEmptyTile()

    def findEmptyTile(self):
        for i in range(3):
            for j in range(3):
                if self.board[i][j] == 0:
                    return (i, j)
        return None

    def is_goal(self):
        return np.array_equal(self.board, [[1, 2, 3], [8, 0, 4], [7, 6, 5]])

    def possibleMoves(self):
        moves = []
        x, y = self.emptyTile
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < 3 and 0 <= ny < 3:
                new_board = np.copy(self.board)
                new_board[x][y], new_board[nx][ny] = new_board[nx][ny], new_board[x][y]
                moves.append(PuzzleState(new_board, self, move=(dx, dy), cost=self.cost + 1))
        return moves

    def __eq__(self, other):
        return np.array_equal(self.board, other.board)

    def __lt__(self, other):
        return self.cost < other.cost

    def __hash__(self):
        return hash(tuple(map(tuple, self.board)))

def h1(state):
    goal = [[1, 2, 3], [8, 0, 4], [7, 6, 5]]
    return sum([1 if state.board[i][j] != 0 and state.board[i][j] != goal[i][j] else 0
                for i in range(3) for j in range(3)])

def a_star(initial_board):
    open_list = []
    initial_state = PuzzleState(np.array(initial_board))
    heapq.heappush(open_list, (0, initial_state))

    closed_set = set()

    while open_list:
        _, current_state = heapq.heappop(open_list)

        if current_state.is_goal():
            break  # Stop processing once goal is reached

        closed_set.add(current_state)

        for neighbor in current_state.possibleMoves():
            if neighbor in closed_set:
                continue

            g = neighbor.cost
            h = h1(neighbor)
            f = g + h

            # Display the g(n) and h(n) values
            print(f"Current State:\n{neighbor.board}")
            print(f"g(n) = {g}, h(n) = {h}, f(n) = {f}\n")

            heapq.heappush(open_list, (f, neighbor))

if __name__ == "__main__":
    initial_board = [[2, 8, 3],
                     [1, 6, 4],
                     [7, 0, 5]]

    print("Solving using Heuristic H1 (Misplaced Tiles)...")
    a_star(initial_board)


Solving using Heuristic H1 (Misplaced Tiles)...
Current State:
[[2 8 3]
 [1 6 4]
 [7 5 0]]
g(n) = 1, h(n) = 5, f(n) = 6

Current State:
[[2 8 3]
 [1 6 4]
 [0 7 5]]
g(n) = 1, h(n) = 5, f(n) = 6

Current State:
[[2 8 3]
 [1 0 4]
 [7 6 5]]
g(n) = 1, h(n) = 3, f(n) = 4

Current State:
[[2 8 3]
 [1 4 0]
 [7 6 5]]
g(n) = 2, h(n) = 4, f(n) = 6

Current State:
[[2 8 3]
 [0 1 4]
 [7 6 5]]
g(n) = 2, h(n) = 3, f(n) = 5

Current State:
[[2 0 3]
 [1 8 4]
 [7 6 5]]
g(n) = 2, h(n) = 3, f(n) = 5

Current State:
[[2 8 3]
 [7 1 4]
 [0 6 5]]
g(n) = 3, h(n) = 4, f(n) = 7

Current State:
[[0 8 3]
 [2 1 4]
 [7 6 5]]
g(n) = 3, h(n) = 3, f(n) = 6

Current State:
[[2 3 0]
 [1 8 4]
 [7 6 5]]
g(n) = 3, h(n) = 4, f(n) = 7

Current State:
[[0 2 3]
 [1 8 4]
 [7 6 5]]
g(n) = 3, h(n) = 2, f(n) = 5

Current State:
[[1 2 3]
 [0 8 4]
 [7 6 5]]
g(n) = 4, h(n) = 1, f(n) = 5

Current State:
[[1 2 3]
 [8 0 4]
 [7 6 5]]
g(n) = 5, h(n) = 0, f(n) = 5

Current State:
[[1 2 3]
 [7 8 4]
 [0 6 5]]
g(n) = 5, h(n) = 2, f(n) = 7

